---
abstract: 'Small, simple timer (stopwatch) object'
author:
  - 'Randy Stauner <rwstauner@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::Util: '0'
  Test::More: '0.96'
  Time::Local: '0'
  perl: '5.006'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Timer-Simple
no_index:
  directory:
    - corpus
    - examples
    - inc
    - share
    - t
    - xt
  namespace:
    - Local
    - t::lib
  package:
    - DB
provides:
  Timer::Simple:
    file: lib/Timer/Simple.pm
    version: '1.005'
requires:
  Carp: '0'
  Time::HiRes: '0'
  overload: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Timer-Simple
  homepage: https://github.com/rwstauner/Timer-Simple
  repository: https://github.com/rwstauner/Timer-Simple.git
version: '1.005'
x_Dist_Zilla:
  perl:
    version: '5.016003'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::RWSTAUNER/Git::NextVersion'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::GenerateFile
      name: '@Author::RWSTAUNER/GenerateManifestSkip'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::RWSTAUNER/GatherDir'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::RWSTAUNER/PruneCruft'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::RWSTAUNER/ManifestSkip'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::RWSTAUNER/PruneDevelCoverDatabase'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::RWSTAUNER/PruneCodeStatCollection'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::RWSTAUNER/PruneTags'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::RWSTAUNER/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::RWSTAUNER/NextRelease'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@Author::RWSTAUNER/Git::Describe'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::RWSTAUNER/PkgVersion'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Author::RWSTAUNER/Prepender'
      version: '1.112280'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugins:
            - '@Author::RWSTAUNER'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Author::RWSTAUNER/SingleEncoding'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::WikiDoc
              name: '@Author::RWSTAUNER/WikiDoc'
              version: '0.093003'
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@Author::RWSTAUNER/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@Author::RWSTAUNER/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Author::RWSTAUNER/Prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@Author::RWSTAUNER/Synopsis'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@Author::RWSTAUNER/Description'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@Author::RWSTAUNER/Overview'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@Author::RWSTAUNER/Usage'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: '@Author::RWSTAUNER/Class Methods'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: '@Author::RWSTAUNER/Attributes'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: '@Author::RWSTAUNER/Methods'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: '@Author::RWSTAUNER/Functions'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Author::RWSTAUNER/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Author::RWSTAUNER/Postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Support
              name: '@Author::RWSTAUNER/Support'
              version: '1.005'
            -
              class: Pod::Weaver::Section::Generic
              name: '@Author::RWSTAUNER/Acknowledgements'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Author::RWSTAUNER/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Contributors
              name: '@Author::RWSTAUNER/Contributors'
              version: '0.007'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Author::RWSTAUNER/Legal'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@Author::RWSTAUNER/List'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::StopWords
              name: '@Author::RWSTAUNER/StopWords'
              version: '1.008'
      name: '@Author::RWSTAUNER/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::RWSTAUNER/License'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::RWSTAUNER/Readme'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::RWSTAUNER/ReadmeAnyFromPod'
      version: '0.133360'
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Author::RWSTAUNER/Bugtracker'
      version: '1.111080'
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::RWSTAUNER/Repository'
      version: '0.19'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::RWSTAUNER/GithubMeta'
      version: '0.42'
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@Author::RWSTAUNER/ContributorsFromGit'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::RWSTAUNER/AutoPrereqs'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::RWSTAUNER/MetaNoIndex'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::RWSTAUNER/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.012'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@Author::RWSTAUNER/MetaProvides::Package'
      version: '1.15000003'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::RWSTAUNER/MinimumPerl'
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::RWSTAUNER/MetaConfig'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::RWSTAUNER/MetaYAML'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::RWSTAUNER/MetaJSON'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::RWSTAUNER/ExecDir'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::RWSTAUNER/ShareDir'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::RWSTAUNER/MakeMaker'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::RWSTAUNER/Test::ReportPrereqs'
      version: '0.013'
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@Author::RWSTAUNER/Test::ChangesHasContent'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@Author::RWSTAUNER/Test::PodSpelling'
      version: '2.006002'
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@Author::RWSTAUNER/@TestingMania/Test::UnusedVars'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::RWSTAUNER/@TestingMania/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::RWSTAUNER/@TestingMania/Test::Version'
      version: '0.002004'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::RWSTAUNER/@TestingMania/PodCoverageTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::RWSTAUNER/@TestingMania/Test::Perl::Critic'
      version: '2.112410'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::RWSTAUNER/@TestingMania/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::RWSTAUNER/@TestingMania/MetaTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::RWSTAUNER/@TestingMania/Test::Kwalitee'
      version: '2.07'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Author::RWSTAUNER/@TestingMania/Test::EOL'
      version: '0.10'
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@Author::RWSTAUNER/@TestingMania/Test::Synopsis'
      version: '2.000004'
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::RWSTAUNER/@TestingMania/Test::DistManifest'
      version: '2.000004'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::RWSTAUNER/@TestingMania/Test::CPAN::Meta::JSON'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::RWSTAUNER/@TestingMania/Test::Compile'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@Author::RWSTAUNER/@TestingMania/Test::Pod::LinkCheck'
      version: '1.001'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::RWSTAUNER/@TestingMania/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::RWSTAUNER/@TestingMania/NoTabsTests'
      version: '0.06'
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@Author::RWSTAUNER/@TestingMania/MojibakeTests'
      version: '0.5'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::RWSTAUNER/@TestingMania/PodSyntaxTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::RWSTAUNER/Manifest'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Author::RWSTAUNER/CheckExtraTests'
      version: '0.016'
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@Author::RWSTAUNER/CheckChangesHasContent'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::CheckMetaResources
      name: '@Author::RWSTAUNER/CheckMetaResources'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::RWSTAUNER/CheckPrereqsIndexed'
      version: '0.010'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::RWSTAUNER/TestRelease'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::RWSTAUNER/@Git/Check'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::RWSTAUNER/@Git/Commit'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::RWSTAUNER/@Git/Tag'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::RWSTAUNER/@Git/Push'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::RWSTAUNER/ConfirmRelease'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::RWSTAUNER/UploadToCPAN'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::RWSTAUNER/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::RWSTAUNER/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.012'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.012'
x_authority: cpan:RWSTAUNER
x_contributors:
  - 'Tomohiro Hosaka <bokutin@bokut.in>'
